# Generated by Django 5.1.3 on 2024-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedorder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='submittedorder',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
